### ISSUE TITLE
samsung upload mode

### ISSUE THREAD

**Issue by itapi** [m4drat/upload-mode-dumper#1]
How to enter that upload mode? 
is it the same as "download mode" or it's a  another special mode for samsung device?
my device is galaxy a24
looking for your reply..I want to try that tool so much... :)

**Comment by m4drat** [comment]
Hi! It's not the same as "download mode". It's a specific "crash" mode which is enabled when a hard fault occurs, e.g., trustzone kernel crash. As far as I know there is no one-size-fits-all solution to enter into upload mode. However, some phones allow to do this from the service menu.

**Comment by itapi** [comment]
@m4drat  thanks for your response sir!
I've tried to enter the sysdump via the 9900 code,and to set the debug level to "mid" and then the device just reboots..nothing else is happening....(galaxy A24)
